import {
  Wrench,
  Sprout,
  Laptop,
  GraduationCap,
  ChefHat,
  Truck,
  FileText,
  Dog,
  Baby,
  Languages,
  Music,
  Scissors,
  Car,
  Paintbrush,
  Heart,
  Dumbbell,
  Camera,
  Shirt,
  Home,
  HelpingHand,
  type LucideIcon,
} from "lucide-react";

export const CATEGORIES = [
  "Bricolage",
  "Jardinage",
  "Informatique",
  "Cours et soutien scolaire",
  "Cuisine",
  "Déménagement et transport",
  "Démarches administratives",
  "Garde d'enfants",
  "Garde d'animaux",
  "Langues",
  "Musique",
  "Coiffure et beauté",
  "Mécanique auto",
  "Peinture et décoration",
  "Aide aux personnes",
  "Sport et bien-être",
  "Photo et vidéo",
  "Couture et retouches",
  "Ménage et repassage",
  "Autre",
] as const;

export type Category = (typeof CATEGORIES)[number];

export function isValidCategory(value: string): value is Category {
  return (CATEGORIES as readonly string[]).includes(value);
}

export const CATEGORY_IMAGES: Record<string, string | null> = {
  Bricolage: "/icones/06_bricolage.png",
  Jardinage: "/icones/04_jardinage.png",
  Informatique: "/icones/05_aide_informatique.png",
  "Cours et soutien scolaire": "/icones/08_soutien_scolaire.png",
  Cuisine: "/icones/07_cuisine.png",
  "Déménagement et transport": "/icones/02_aide_au_demenagement.png",
  "Démarches administratives": "/icones/20_aide_administrative.png",
  "Garde d'enfants": "/icones/03_baby_sitting.png",
  "Garde d'animaux": "/icones/10_garde_animaux.png",
  Langues: "/icones/17_traduction.png",
  Musique: "/icones/01_cours_de_guitare.png",
  "Coiffure et beauté": null,
  "Mécanique auto": "/icones/19_reparation_velo.png",
  "Peinture et décoration": "/icones/14_peinture_renovation.png",
  "Aide aux personnes": "/icones/23_aide_personnes_agees.png",
  "Sport et bien-être": "/icones/13_yoga_bien_etre.png",
  "Photo et vidéo": "/icones/09_photographie.png",
  "Couture et retouches": "/icones/18_couture.png",
  "Ménage et repassage": "/icones/12_menage.png",
  Autre: null,
};

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  Bricolage: Wrench,
  Jardinage: Sprout,
  Informatique: Laptop,
  "Cours et soutien scolaire": GraduationCap,
  Cuisine: ChefHat,
  "Déménagement et transport": Truck,
  "Démarches administratives": FileText,
  "Garde d'enfants": Baby,
  "Garde d'animaux": Dog,
  Langues: Languages,
  Musique: Music,
  "Coiffure et beauté": Scissors,
  "Mécanique auto": Car,
  "Peinture et décoration": Paintbrush,
  "Aide aux personnes": Heart,
  "Sport et bien-être": Dumbbell,
  "Photo et vidéo": Camera,
  "Couture et retouches": Shirt,
  "Ménage et repassage": Home,
  Autre: HelpingHand,
};
